# Generated by Django 3.2 on 2023-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230417_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pdf_file',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
