# Generated by Django 3.2 on 2023-05-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractCV',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.employee')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiter')),
            ],
        ),
    ]
