# Generated by Django 3.2 on 2023-05-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extractcv_jobrequirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequirement',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='extractcv',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='pdf_upload',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
