# Generated by Django 3.2 on 2023-05-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230503_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequirement',
            old_name='recruter',
            new_name='recruiter',
        ),
    ]
