# Generated by Django 3.2 on 2023-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_recruter_jobrequirement_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dq6avgw6n/image/upload/v1683965956/2_lrrhqr.jpg', max_length=1000, null=True),
        ),
    ]
