# Generated by Django 3.2 on 2023-06-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employee_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractcv',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extract_cv', serialize=False, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='accounts.recruiter'),
        ),
    ]
