# Generated by Django 3.2 on 2023-06-06 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230604_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
