pipeline {

    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('BackEnd') {
                    script {
                        try {
                            sh "ls"
                            sh "mv docker.env .env"
                            echo "Done reading environment"
                        }
                        catch (err) {
                            echo err.getMessage()
                        }
                    }
                    // sh "pip3 install -r requirements.txt"
                    echo "Done installing dependencies"
                }
            }
        }
        stage("Clear") {
            steps {
                dir('BackEnd'){
                    script {
                        try {
                            sh "docker rm hire_it_api -f"
                            sh "docker rmi hire_it -f"
                        }
                        catch (err) {
                            echo err.getMessage()
                        }
                    }
                }
            }
        }
        stage('Build and Deploy') {
            steps {
                dir('BackEnd')
                {
                    sh "docker compose up --build -d"
                }
               
            }
        }
    }
}
